### ISSUE TITLE
How to not unmount inactive panels?

### ISSUE THREAD

**Issue by jojonarte** [usabilityhub/react-context-tabs#6]
I'm currently having a problem with my implementation.

My Tab Component below: 
https://pastebin.com/LuTH3Pw3

*** EXPECTED
I expect the children components of each tab to be retained and not unmounted on deselect or when inactive.

*** ACTUAL
I am using above component and just passing a dynamic amount of Tab children which I want to be unique from each other dynamically. I expect that the inactive children will just be inactive and not unmounted but upon checking each previously selected children is unmounted when I toggle a different tab.

**Comment by rhys-vdw** [comment]
Hi @jojonarte! Thanks for checking out this library. Just to be clear–you mean that you want the `TabPanel`'s children to remain mounted (As opposed to the `Tab` itself)?

If so you can use [`PersistentTabPanel`](https://github.com/usabilityhub/react-context-tabs#persistenttabpanel) for this.

Just beware that [updates are currently disabled](https://github.com/usabilityhub/react-context-tabs/blob/814c5706e3e73eee4cbff38ba9e262b195a926ce/src/PersistentTabPanel.js#L35-L37) when the tab is deselected. If this causes issues for you I'll be happy to do a quick fix. This optimization was a bit misguided and can cause issues in some cases.

**Comment by jojonarte** [comment]
@rhys-vdw This is definitely what I needed. I didn't notice the `PersistentTabPanel` at first. Thank you.

**Comment by jojonarte** [comment]
@rhys-vdw there's a little bit of problem relating to the updates being disabled. One instance I've replicated is that if the child I'm passing to the `PersistentTabPanel` has not yet finished moving to all it's states i.e mount -> loading -> complete if it is stuck in loading when I reselect it again after switching from another it will still be stucked in that state and will not continue to completion.

I've created a workaround for this by adding a prop to `PersistentTabPanel` so we force updates to persist while unselected.

**Comment by rhys-vdw** [comment]
Ah damn. I will fix this next week, but for now you can use this:

```jsx
import React from 'react'
import PropTypes from 'prop-types'
import classNames from 'classnames'

export default function PersistentTabPanel ({ children, className, tabId }, { selectedTabId }) {
  const style = tabId === selectedTabId ? undefined : { display: "none" }
  return (
    <section className={classNames('TabPanel', className)} style={style}>
      {children}
    </section>
  )
}

TabPanel.propTypes = {
  children: PropTypes.node,
  tabId: PropTypes.any.isRequired
}

TabPanel.contextTypes = {
  selectedTabId: PropTypes.any
}
```

**Comment by rhys-vdw** [comment]
I've reopened the issue to remind me to fix it.

**Comment by rhys-vdw** [comment]
(I didn't test that code btw, but it should be pretty clear)

**Comment by jojonarte** [comment]
@rhys-vdw with this implementation processes even on the active tab is comparatively slower.

**Comment by rhys-vdw** [comment]
@jojonarte yes, you should prefer to use the normal `TabPanel` component. If you're losing state when the component unmounts you're probably storing it in the wrong place. Move the state up higher in your component tree.

eg.

```jsx
class MyTabs extends Component {
  state = {
    clickCount: 0
  }

  incrementClickCount() { this.setState({ clickCount: this.state.clickCount + 1 }) }

  render() {
    return (
      <Tabs defaultTabId="clicker">
        <TabList>
          <Tab tabId="clicker">Clicker</Tab>
          <Tab tabId="counter">Counter</Tab>
        </TabList>
        <TabPanel tabId="clicker"><Clicker onClick={this.incrementClickCount} /></TabPanel>
        <TabPanel tabId="counter"><Counter count={this.state.clickCount} /></TabPanel>
      </Tabs>
    )
  }
}
```

**Comment by rhys-vdw** [comment]
Or alternatively you can store your state in redux/mobx etc.

**Comment by jojonarte** [comment]
@rhys-vdw The state is actually a bit hard to manage for me, as what I'm putting inside each tab are not states that can controlled by react directly, or maybe my implementation is not good. I'm actually putting different instances of `tradingview/charting_library` view inside each tab. The `charting_library ` has it's own state and processes handled by datafeed. I'm still looking into it on which angle I could tackle this problem.  😄

**Comment by rhys-vdw** [comment]
My use case for `PersistentTabPanel` is a wordcloud rendered with d3. Similar kind of thing, it was expensive to mount, so I wanted to initialize it lazily when the tab is first accessed and then keep it mounted for future tab navigations.

I take it that the overhead is because now all of your tabs are being updated when the state changes, even though they're not visible?

**Comment by jojonarte** [comment]
@rhys-vdw Yes, that's what's happening. How did you approach solving your usecase with d3?

**Comment by rhys-vdw** [comment]
I just use the `PersistentTabPanel` that is part of the library. It defers first render until mount and prevents updates while invisible.

I am actually going to do some work on this this afternoon. I think I might try making the `PersistentTabPanel` prevent mount until first visible, but then accept updates after that. Not perfect, but I think any other optimization might require some custom code depending on the use case.

**Comment by rhys-vdw** [comment]
Hey @jojonarte I just released `2.0.0-alpha` with a bunch of fixes. Can you give it a try? I made some changes to`PersistentTabPanel` so you should be able to use the one from the module now. If it's all good I'll release 2.0.0.

**Comment by jojonarte** [comment]
The new version seems to have different way of layouting the `TabsList` and `TabPanel`.

**Comment by rhys-vdw** [comment]
Oh really? It didn't make any difference in the UsabilityHub code. Is it a problem? AFAIK you're the only other user so lemme know if you'd like anything to change.

**Comment by jojonarte** [comment]
Before I actually applied style to the `className` I passed to `Tabs`, but I think it's better now. I just have to wrap it with div and pass the `className` to it.

**Comment by rhys-vdw** [comment]
Ah yes, that did change! The new context API doesn't create an element (I wrote the original before `Fragment` was available).

FYI I released `2.0.0-alpha2` because `2.0.0-alpha` was emitting ES5 with `const` etc.

**Comment by jojonarte** [comment]
Cool, I'll check it out.

**Comment by rhys-vdw** [comment]
I'm gonna close this one now. ✌
